version: "3.9"

services:
  banking-service:
    image: sanara/banking-service:v1
    container_name: banking-service-container
    environment:
      - QUARKUS_CLIENT_HTTP=http://banking-validation:8181  # chama o container da validation
      - QUARKUS_DATASOURCE_USERNAME=sanara
      - QUARKUS_DATASOURCE_PASSWORD=T@njiro192168
      - QUARKUS_DATASOURCE_HOST=postgres-db-service
      - QUARKUS_DATASOURCE_PORT=5432
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db-service
      - banking-validation

  postgres-db-service:
    image: postgres:14
    container_name: postgres-db-service-container
    environment:
      - POSTGRES_USER=sanara
      - POSTGRES_PASSWORD=T@njiro192168
      - POSTGRES_DB=agencia
    ports:
      - "5435:5432" # evitar conflito
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data_service:/var/lib/postgresql/data

  banking-validation:
    image: sanara/banking-validation:v2
    container_name: banking-validation-container-service
    environment:
      - QUARKUS_DATASOURCE_USERNAME=sanara
      - QUARKUS_DATASOURCE_PASSWORD=T@njiro192168
      - QUARKUS_DATASOURCE_HOST=postgres-db-validation-service
      - QUARKUS_DATASOURCE_PORT=5432
    depends_on:
      - postgres-db-validation-service

  postgres-db-validation-service:
    image: postgres:14
    container_name: postgres-db-validation-service-container
    environment:
      - POSTGRES_USER=sanara
      - POSTGRES_PASSWORD=T@njiro192168
      - POSTGRES_DB=agencia
    ports:
      - "5436:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data_validation_service:/var/lib/postgresql/data

volumes:
  postgres_data_service:
  postgres_data_validation_service:
